server:
  port: 8761 #eureka默认端口号 8761
eureka:
  client:
    fetch-registry: false  #eureka服务不从注册中心获取
    register-with-eureka: false #eureka服务不注册到注册中心
    service-url:
      defaultZone: http://localhost:8761/eureka/ #指定注册中心地址
  instance:
    hostname: eureka-server #注册中心名称
