server:
  port: 8001 #服务提供者端口
spring:
  application:
    name: provider-ticket #服务提供者名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
  instance:
    hostname: eureka-server #注册中心名称
    prefer-ip-address: true #通过ip注册到注册中心

